# Generated by Django 3.1.5 on 2022-11-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Ad Soyad')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('message', models.CharField(max_length=200, verbose_name='Mesaj')),
                ('phone_num', models.CharField(max_length=11, verbose_name='Telefon Numarası')),
            ],
        ),
    ]
