# Generated by Django 4.1.3 on 2022-12-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformmodel',
            options={'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar'},
        ),
    ]
