# Generated by Django 4.1.3 on 2022-11-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20221128_0123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
