# Generated by Django 3.1.5 on 2022-11-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='nameSurname',
            field=models.CharField(default='bilal', max_length=30),
            preserve_default=False,
        ),
    ]
