# Generated by Django 3.1.5 on 2022-11-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_book_namesurname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('surname', models.CharField(max_length=50, verbose_name='Soyad')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('your_phone', models.CharField(max_length=200, verbose_name='Mesaj')),
                ('phone_num', models.CharField(max_length=11, verbose_name='Telefon Numarası')),
                
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
