# Generated by Django 4.1.3 on 2022-11-30 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_service_alter_appointment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('Erkek', 'Erkek'), ('Dişi', 'Dişi')], default='Erkek', max_length=50, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hayvan',
            field=models.CharField(choices=[('Kedi', 'Kedi'), ('Köpek', 'Köpek'), ('Kuş', 'Kuş'), ('Diğer', 'Diğer')], default='Kedi', max_length=50, verbose_name='Hayvan'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 30, 20, 13, 4, 151195), max_length=50, verbose_name='Ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='surname',
            field=models.CharField(default='', max_length=50, verbose_name='Soyad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Aşlar ve Takibi', 'Aşlar ve Takibi'), ('Doğum ve Jinekoloji Hizmetleri', 'Doğum ve Jinekoloji Hizmetleri'), ('Cerrahi Operasyonlar', 'Cerrahi Operasyonlar'), ('Parazit Tedavisi', 'Parazit Tedavisi'), ('Röntgen/Ultrason', 'Röntgen/Ultrason'), ('Diş ve Dişeti Tedavisi', 'Diş ve Dişeti Tedavisi')], default='Aşlar ve Takibi', max_length=50, verbose_name='Hizmet'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('09:00 - 10:00', '09:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 13:00', '12:00 - 13:00'), ('13:00 - 14:00', '13:00 - 14:00'), ('14:00 - 15:00', '14:00 - 15:00'), ('15:00 - 16:00', '15:00 - 16:00'), ('16:00 - 17:00', '16:00 - 17:00'), ('17:00 - 18:00', '17:00 - 18:00')], default='3 PM', max_length=50, verbose_name='Saat'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_ordered',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Randevu Alma Saati'),
        ),
        migrations.AlterModelTable(
            name='appointment',
            table=None,
        ),
    ]
