# Generated by Django 4.1.3 on 2022-12-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_appointment_email_appointment_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Randevu', 'verbose_name_plural': 'Randevular'},
        ),
    ]
