# Generated by Django 3.1.5 on 2022-11-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Ürün Adı')),
                ('price', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop')),
            ],
        ),
    ]
