# Generated by Django 3.1.5 on 2022-11-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(help_text='Ürün adını giriniz', max_length=50, unique=True, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Fiyat'),
        ),
    ]
