# Generated by Django 4.1.3 on 2022-12-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20221124_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
    ]
