# Generated by Django 4.1.3 on 2022-11-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_appointment_user_appointment_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='hayvan',
            new_name='animal',
        ),
    ]
